//
// Created by riedel on 21/11/20.
//

#ifndef INC_7542_TALLER_PAGES_INVALIDRESOURCEEXCEPTION_H
#define INC_7542_TALLER_PAGES_INVALIDRESOURCEEXCEPTION_H


class InvalidResourceException {

};


#endif //INC_7542_TALLER_PAGES_INVALIDRESOURCEEXCEPTION_H
