//
// Created by riedel on 7/11/20.
//

#ifndef INC_7542_TALLER_PAGES_SOCKETEXCEPTION_H
#define INC_7542_TALLER_PAGES_SOCKETEXCEPTION_H


class socketException {

};


#endif //INC_7542_TALLER_PAGES_SOCKETEXCEPTION_H
