//
// Created by riedel on 22/11/20.
//

#ifndef INC_7542_TALLER_PAGES_PETITIONINVALID_H
#define INC_7542_TALLER_PAGES_PETITIONINVALID_H


class PetitionInvalid {

};


#endif //INC_7542_TALLER_PAGES_PETITIONINVALID_H
