//
// Created by riedel on 22/11/20.
//

#ifndef INC_7542_TALLER_PAGES_PETITIONPROCESSOR_H
#define INC_7542_TALLER_PAGES_PETITIONPROCESSOR_H


class PetitionProcessor {

};


#endif //INC_7542_TALLER_PAGES_PETITIONPROCESSOR_H
