//
// Created by riedel on 22/11/20.
//

#ifndef INC_7542_TALLER_PAGES_PETITIONGETROOT_H
#define INC_7542_TALLER_PAGES_PETITIONGETROOT_H


class PetitionGetRoot {

};


#endif //INC_7542_TALLER_PAGES_PETITIONGETROOT_H
