//
// Created by riedel on 21/11/20.
//

#ifndef INC_7542_TALLER_PAGES_RESOURCESMONITOR_H
#define INC_7542_TALLER_PAGES_RESOURCESMONITOR_H


class resourcesMonitor {

};


#endif //INC_7542_TALLER_PAGES_RESOURCESMONITOR_H
